# Generated by Django 3.1.1 on 2020-09-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200919_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(default='null', upload_to='posts/photos'),
            preserve_default=False,
        ),
    ]
